services:
  - type: web
    name: rl-presentation
    runtime: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
