services:
  - type: web
    name: rl-presentation
    runtime: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: python server/app.py
    envVars:
      - key: PORT
        value: 10000
