services:
  - type: web
    name: rl-presentation
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && gunicorn --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - --log-level debug app:app
